services:
  web:
    image: assistchat-api-local
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db

  botworker:
    image: assistchat-api-local
    env_file: .env
    restart: unless-stopped
    command: python src/app/modules/bot/worker_entry.py
    depends_on:
      - db

  db:
    image: postgres:16.9
    env_file: .env
    volumes:
      - assistchat_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  assistchat_db:
